package com.ynyes.lyz.repository;

import java.util.Date;
import java.util.List;

import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.PagingAndSortingRepository;

import com.ynyes.lyz.entity.TdReceipt;

/**
 *  收款报表持久层
 * 
 * @author yanle
 *
 */

public interface TdReceiptRepo extends PagingAndSortingRepository<TdReceipt, Long>, JpaSpecificationExecutor<TdReceipt> {
	
	
	/**
	 * 调用存储过程
	 * @return
	 */
	@Query(value = "{call insertReceipt_initial_copy(?1,?2,?3)}",nativeQuery = true)
	void callInsertReceipt(Date start,Date end,String username);
	
	@Query(value=" SELECT "
			+" 	UUID() id, "
			+" 	o.diy_site_name diy_site_name, "
			+" 	'收款'  receipt_type, "
			+" 	o.main_order_number main_order_number, "
			+" 	o.order_number order_number, "
			+"  o.user_id user_id, "
			+" 	o.real_user_real_name real_user_real_name, "
			+" 	o.username username, "
			+" 	o.seller_real_name seller_real_name, "
			+" 	o.order_time order_time, "
			+" 	o.deliver_type_title deliver_type_title, "
			+" 	o.pay_time receipt_time, "
			+" 	SUM(IFNULL(o.actual_pay, 0)) actual_pay, "
			+" 	SUM(IFNULL(o.other_pay, 0)) other_pay, "
			+" 	0 diy_cash, "
			+" 	0 diy_pos, "
			+" 	0 diy_other, "
			+"  SUM((IFNULL(o.actual_pay, 0) + IFNULL(o.other_pay, 0))) summary, "
			+"	NULL AS real_pay_time, "
			+" 	c.city_name city_name, "
			+" 	?6 create_username, "
			+" 	o.diy_site_code diy_site_code, "
			+" 	o.diy_site_id diy_id, "
			+"  owd.serial_number serial_number "
			+" FROM "
			+" 	td_order o left join td_own_money_record owd on o.main_order_number = owd.order_number, "
			+"  td_diy_site diy, "
			+" td_city c "	
			+" WHERE o.diy_site_code = diy.store_code "
			+"	and diy.city_id = c.id "
			+" 	and o.status_id NOT IN (1, 2, 7, 8) "
			+" AND ( "
			+" 	o.actual_pay != 0 "
			+" 	OR o.other_pay != 0 "
			+" ) "
			+" AND o.pay_time >= ?1 "
			+" AND o.pay_time <= ?2 "
			+" AND c.city_name LIKE ?3 "
			+" AND o.diy_site_code LIKE ?4 "
			+" AND o.diy_site_id IN ?5  GROUP BY main_order_number "
			+" UNION ALL "
			+" SELECT DISTINCT "
			+" 	UUID() id, "
			+" 	o.diy_site_name diy_site_name, "
			+" 	'收款' receipt_type, "
			+" 	o.main_order_number main_order_number, "
			+" 	o.order_number order_number, "
			+"	o.user_id user_id, "
			+" 	o.real_user_real_name real_user_real_name, "
			+" 	o.username username, "
			+" 	o.seller_real_name seller_real_name, "
			+" 	o.order_time order_time, "
			+" 	o.deliver_type_title deliver_type_title, "
			+" 	o.pay_time receipt_time, "
			+" 	SUM(IFNULL(o.actual_pay, 0)) actual_pay, "
			+" 	SUM(IFNULL(o.other_pay, 0)) other_pay, "
			+" 	o.cash_pay diy_cash, "
			+" 	o.pos_pay diy_pos, "
			+" 	o.back_other_pay diy_other, "
			+" 	SUM( "
			+" 		( "
			+" 			IFNULL(o.actual_pay, 0) +IFNULL(o.other_pay, 0)+IFNULL(o.cash_pay,0)+IFNULL(o.pos_pay,0)+IFNULL(o.back_other_pay,0) "
			+" 		) "
			+" 	) summary, "
			+"	owd.real_pay_time AS real_pay_time, "
			+" 	c.city_name city_name, "
			+" 	?6 create_username, "
			+" 	o.diy_site_code diy_site_code, "
			+" 	o.diy_site_id diy_id, "
			+"  owd.serial_number serial_number "
			+" FROM "
			+" 	td_order o left join td_own_money_record owd on o.main_order_number = owd.order_number, "
			+" 	td_diy_site diy, "
			+" 	td_city c "
			+" WHERE "
			+" o.diy_site_code = diy.store_code "
			+" AND diy.city_id = c.id "
			+" AND o.status_id NOT IN (1, 2, 7, 8) "
			+" AND ( "
			+" 	o.cash_pay != 0 "
			+" 	OR o.pos_pay != 0 "
			+" 	OR o.back_other_pay != 0 "
			+" ) "
			+" AND o.pay_time >= ?1 "
			+" AND o.pay_time <= ?2 "
			+" AND c.city_name LIKE ?3 "
			+" AND o.diy_site_code LIKE ?4 "
			+" AND o.is_coupon=1 "
			+" AND o.diy_site_id IN ?5 "
			+" GROUP BY "
			+" 	main_order_number "
			+" UNION ALL "
			+" 	SELECT  distinct UUID() id , "
			+" 		o.diy_site_name diy_site_name, "
			+" 		'收款' receipt_type, "
			+" 		o.main_order_number main_order_number, "
			+" 		o.order_number order_number, "
			+"		o.user_id user_id, "
			+" 		o.real_user_real_name real_user_real_name, "
			+" 		o.username username, "
			+" 		o.seller_real_name seller_real_name, "
			+" 		o.order_time order_time, "
			+" 		o.deliver_type_title deliver_type_title, "
			+" 		CASE o.deliver_type_title "
			+" 	WHEN '送货上门' THEN "
			+" 		owd.own_time "
			+" 	WHEN '门店自提' THEN "
			+" 		owd.pay_time "
			+" 	END receipt_time, "
			+" 	0 actual_pay, "
			+" 	0 other_pay, "
			+" 	IFNULL(owd.back_money, 0) diy_cash, "
			+" 	IFNULL(owd.back_pos, 0) diy_pos, "
			+" 	IFNULL(owd.back_other, 0) diy_other, "
			+"  (IFNULL(owd.back_money, 0) + IFNULL(owd.back_pos, 0) + IFNULL(owd.back_other, 0)) summary, "
			+"  owd.real_pay_time real_pay_time, "
			+" 	c.city_name city_name,  "
			+" 	?6 create_username, "
			+" 	o.diy_site_code diy_site_code, "
			+" 	o.diy_site_id diy_id, "
			+"  owd.serial_number serial_number "
			+" FROM "
			+" 	td_order o, "
			+" 	td_own_money_record owd, "
			+" td_diy_site diy, "
			+" td_city c "	
			+" WHERE o.diy_site_code = diy.store_code "
			+" and diy.city_id = c.id "
			+" and owd.order_number = o.main_order_number "
			+" AND o.status_id NOT IN (1, 2, 7, 8) "
			+" AND ( "
			+" 	owd.back_money != 0 "
			+" 	OR owd.back_pos != 0 "
			+" 	OR owd.back_other != 0 "
			+" ) "
			+" AND ( "
			+" 	CASE o.deliver_type_title "
			+" 	WHEN '送货上门' THEN "
			+" 		owd.own_time "
			+" 	WHEN '门店自提' THEN "
			+" 		owd.pay_time "
			+" 	END "
			+" ) >=?1 "
			+" AND ( "
			+" 	CASE o.deliver_type_title "
			+" 	WHEN '送货上门' THEN "
			+" 		owd.own_time "
			+" 	WHEN '门店自提' THEN "
			+" 		owd.pay_time "
			+" 	END "
			+" ) <= ?2 "
			+" AND c.city_name LIKE ?3 "
			+" AND o.diy_site_code LIKE ?4 "
			+" AND o.diy_site_id IN ?5 GROUP BY main_order_number "
			+" UNION ALL  "
			+" SELECT " 
			+" 	UUID() id, " 
			+"	o.diy_site_name diy_site_name, "
			+" 	'退款' recceipt_type, " 
			+" 	o.main_order_number main_order_number, " 
			+" 	rn.return_number order_number, " 
			+"	o.user_id user_id, "
			+" 	o.real_user_real_name real_user_real_name, " 
			+" 	o.username username, " 
			+" 	o.seller_real_name seller_real_name, " 
			+" 	rn.order_time order_time, " 
			+" 	o.deliver_type_title deliver_type_title, " 
			+" 	rn.return_time receipt_time, " 
			+" 	IFNULL(- ri.prepay_amt, 0) actual_pay, " 
			+" 	IFNULL(NULL, 0) other_pay, " 
			+" 	IFNULL(- cr.money, 0) diy_cash, " 
			+" 	IFNULL(NULL, 0) diy_pos, " 
			+" 	IFNULL(NULL, 0) diy_other, " 
			+" 	( " 
			+" 		IFNULL(- ri.prepay_amt, 0) + IFNULL(- cr.money, 0) " 
			+" 	) summary, " 
			+" 	NULL AS real_pay_time, " 
			+" 	diy.city city_name, " 
			+" 	?6 create_username, " 
			+" 	diy.store_code diy_site_code, " 
			+" 	diy.id diy_site_id, "
			+"  null serial_number "
			+" FROM " 
			+" 	td_return_note rn " 
			+" LEFT JOIN td_order o ON rn.order_number = o.order_number "
//			+" INNER JOIN td_own_money_record owd on o.main_order_number = owd.order_number "
			+" LEFT JOIN td_cash_return_note cr ON rn.return_number = cr.return_note_number " 
			+" LEFT JOIN td_return_order_inf ri ON rn.return_number = ri.return_number " 
			+" LEFT JOIN td_diy_site diy ON rn.diy_site_id = diy.id " 
			+" WHERE rn.status_id=5 " 
			+" AND (ri.prepay_amt>0 OR cr.money>0) " 
			+" AND rn.return_time>= ?1 " 
			+" AND rn.return_time<= ?2 " 
			+" AND diy.city LIKE ?3 " 
			+" AND diy.store_code LIKE ?4 " 
			+" AND diy.id in ?5 " 
			+" ORDER BY receipt_time DESC; " ,nativeQuery=true)
	List<TdReceipt> queryDownList(Date begin, Date end, String cityName, String diySiteCode,  List<String> roleDiyIds,String username);
	
	
	
}
