server:
  port: 10001
  
spring:
  profiles:
    active: dev
  datasource:
    initialSize: 10
    minIdle: 10
    maxActive: 60
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000;druid.stat.logSlowSql=true;
  freemarker:
    charset: utf8
  jpa:
    hibernate: 
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: false
      
---

#开发环境
spring:
  profiles: dev
  jpa:
    show-sql: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource:
    url: jdbc:mysql://localhost:3306/lyz?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

deploy:
  image-path: src/main/resources/static/images
  alipay:
    url: http://test.leyizhuang.com.cn/pay/alipay/return
    async: 
      url: http://test.leyizhuang.com.cn/pay/alipay/return/async
  wechat:
    async:
      url: http://test.leyizhuang.com.cn/pay/wechat/return/async
  oss:
    cdnHosts: img-dev.leyizhuang.com.cn
    folder: app/images/
    bucket: leyizhuang-dev
  wms:
    url: http://120.76.214.99:8199/WmsInterServer.asmx?wsdl
  ebs: 
    url: http://erptest.zghuarun.com:8030/webservices/SOAProvider/plsql/cux_app_webservice_pkg/?wsdl
    newUrl: http://ebs.leyizhuang.com.cn:10001/ebs/
      
---

#测试环境
spring:
  profiles: test
  jpa:
    show-sql: false
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource:
    url: jdbc:mysql://localhost:3306/lyz?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

deploy:
  image-path: /mnt/root/images/goods
  alipay:
    url: http://test.leyizhuang.com.cn/pay/alipay/return
    async: 
      url: http://test.leyizhuang.com.cn/pay/alipay/return/async
  wechat:
    async:
      url: http://test.leyizhuang.com.cn/pay/wechat/return/async
  oss:
    cdnHosts: img-dev.leyizhuang.com.cn
    folder: app/images/
    bucket: leyizhuang-dev
  wms: 
    url: http://120.76.214.99:8199/WmsInterServer.asmx?wsdl
  ebs: 
    url: http://erptest.zghuarun.com:8030/webservices/SOAProvider/plsql/cux_app_webservice_pkg/?wsdl
    newUrl: http://ebs.leyizhuang.com.cn:10001/ebs/
      
---

#生产环境
spring:
  profiles: prod
  jpa:
    show-sql: false
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource:
    url: jdbc:mysql://rm-wz9805x7ngck809dg.mysql.rds.aliyuncs.com:3306/lyz?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=true
    username: magpie
    password: LEyizhuang2017
    driver-class-name: com.mysql.jdbc.Driver

deploy:
  image-path: /mnt/root/images/goods
  alipay:
    url: http://www.leyizhuang.com.cn/pay/alipay/return
    async: 
      url: http://www.leyizhuang.com.cn/pay/alipay/return/async
  wechat:
    async:
      url: http://www.leyizhuang.com.cn/pay/wechat/return/async
  oss:
    cdnHosts: img1.leyizhuang.com.cn,img2.leyizhuang.com.cn,img3.leyizhuang.com.cn,img4.leyizhuang.com.cn,img5.leyizhuang.com.cn
    folder: app/images/
    bucket: leyizhuang
  wms: 
    url: http://120.76.23.226:8999/WmsInterServer.asmx?wsdl
  ebs: 
    url: http://erpap.zghuarun.com:8008/webservices/SOAProvider/plsql/cux_app_webservice_pkg/?wsdl
    newUrl: http://ebs.leyizhuang.com.cn:10001/ebs/

 